# Generated by Django 6.1.1 on 2026-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('advisory_text', models.TextField()),
                ('category', models.CharField(choices=[('irrigation', 'Irrigation'), ('pest', 'Pest Alert'), ('sowing', 'Sowing'), ('harvest', 'Harvest')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial.panchayat')),
            ],
        ),
    ]
