# Generated by Django 6.0.5 on 2026-09-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tamil_name', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Jun-Oct)'), ('rabi', 'Rabi (Nov-Mar)'), ('zaid', 'Zaid (Apr-Jun)')], max_length=20)),
                ('growth_stages', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropAdvisoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(max_length=50)),
                ('condition', models.JSONField(default=dict)),
                ('advisory_text', models.TextField()),
                ('advisory_tamil', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='advisory.crop')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('heatwave', 'Heatwave'), ('coldwave', 'Cold Wave'), ('storm', 'Storm')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('message_tamil', models.TextField(blank=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial.panchayat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
