# Generated by Django 6.0.5 on 2026-09-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('confidence', models.FloatField()),
                ('pest_types', models.JSONField(default=list)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial.panchayat')),
            ],
            options={
                'unique_together': {('panchayat', 'date')},
            },
        ),
    ]
