# Generated by Django 6.1.1 on 2026-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('humidity', models.FloatField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial.block')),
            ],
            options={
                'unique_together': {('block', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PanchayatForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('humidity', models.FloatField()),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial.panchayat')),
            ],
            options={
                'unique_together': {('panchayat', 'date')},
            },
        ),
    ]
